### ISSUE TITLE
Is nose necessary?

### ISSUE THREAD

**Issue by mjtamlyn** [orf/django-choice-object#6]
Is there any reason why we are using nose tests? Running `python django_choice_object/tests.py` would be just as simple, and seems like it should be possible given the `__main__` block at the bottom of the file. You can't run either option at will due to the different python paths/imports. Perhaps actually just having a top level `tests.py` which runs with unittest and is outside of the shipped package would make most sense.

**Comment by orf** [comment]
Probably not to be honest, there are a few things I'd like to fix with this library and that's one of them. I'd quite like to base it off the standard `enum` type that ships with Python now as well but I'm not sure how, and I don't have the time to make it happen at the moment :(

I'll accept pull requests though if it's bothering you, I've got no objections to a top level `tests.py` file :+1:

**Comment by orf** [comment]
Closed via e6cecd5fa708f2d1b8d366659cb237b8a97225ce
